services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_APP_URL_CANONICAL: ${NEXT_PUBLIC_APP_URL_CANONICAL}
    restart: on-failure:1
    ports:
      - 3000
    env_file:
      - ./.env
    command: yarn run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
