# Développement
FROM node:22-slim AS dev

WORKDIR /app
RUN apt-get update && apt-get install -y \
    curl \
    openssl \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn set version stable
RUN yarn install --immutable

COPY . .

EXPOSE 3000

CMD ["yarn", "run", "start:dev"]