-- AlterTable
ALTER TABLE "public"."Estimate" ADD COLUMN     "validFrom" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "public"."Invoice" ADD COLUMN     "validFrom" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "validUntil" SET DEFAULT CURRENT_TIMESTAMP;
